import {
  builderAddons,
  builderFreightOptions,
  builderServices,
  countryContentDefaults,
  faqList,
  productBenefits,
  productCategories,
  sourcingMatrixRows,
  sourcingSteps,
  trainingCurriculum,
  trainingEcosystemItems,
  trainingFormats,
} from '../../../pages/services/servicesData';

export const DEFAULTS = {
  badge: 'End-to-End Procurement Infrastructure',
  headline: 'Integrated Global Trading Solutions',
  subheadline: 'From factory-direct auditing and private label OEM formulation to Ministry permits, GDCE customs clearance, and door-to-door logistics in Cambodia.',
  headline_highlight: 'Your Enterprise',
  tab_all: 'All Services',
  tab_product: '01. Product Sales',
  tab_sourcing: '02. Sourcing-as-a-Service',
  tab_training: '03. Sales Training',
  product_badge: 'Service 01 — Local Stock Distribution',
  product_title: 'Product Sales',
  product_highlight: '(Local Cambodian Inventory)',
  product_desc: 'Skip foreign supplier risk and international freight delays. We import premium goods directly, verify quality, and hold local stock in Phnom Penh ready for immediate delivery.',
  product_cta: 'Browse Live Wholesale Stock',
  origin_selector_label: 'Select Origin Country',
  source_from_label: 'Source from',
  corridor_overview_label: 'Overview',
  compliance_standards_label: 'Compliance Standards',
  top_products_label: 'Top Sourced Products',
  stock_categories_label: 'Product Categories Available in Stock',
  origin_countries: countryContentDefaults,
  product_categories: productCategories,
  product_benefits: productBenefits,
  sourcing_badge: 'Service 02 — Custom B2B Procurement Desk',
  sourcing_title: 'Sourcing-as-a-Service',
  sourcing_highlight: '(Factory Procurement)',
  sourcing_desc: 'Need a custom product made abroad? UNT acts as your external procurement team — handling factory audits, price negotiation, sample inspection, freight, and GDCE customs clearance.',
  sourcing_cta: 'Request Custom B2B Sourcing',
  sourcing_roadmap_title: '5-Phase Procurement Roadmap',
  sourcing_roadmap_hint: 'Click any step',
  sourcing_phase_label: 'Phase',
  sourcing_details_label: 'Details',
  sourcing_start_phase_label: 'Start Phase',
  sourcing_steps: sourcingSteps,
  sourcing_manage_title: 'What We Manage For You',
  sourcing_manage_items_text: 'Supplier research & factory background vetting\nWholesale price negotiation & contract terms\nPhysical sample inspection & lab testing\nGDCE customs clearance & Ministry certificates',
  sourcing_terms_title: 'Key Terms & MOQs',
  sourcing_moq_label: 'Minimum Order Quantity:',
  sourcing_moq_value: 'Flexible and negotiated with our specialists based on product type.',
  sourcing_countries_label: 'Countries Covered:',
  sourcing_countries_value: 'Japan, South Korea, Malaysia, Vietnam, Laos, China.',
  sourcing_scope_label: 'Product Scope:',
  sourcing_scope_value: 'Food, Supplements, Skincare, Hair Care, Wellness, Household.',
  training_badge: 'Service 03 — Sales Academy & Ecosystem',
  training_title: 'Sales Training &',
  training_highlight: 'Ecosystem Enablement',
  training_desc: "Transform your sales team into high-revenue closer teams. We teach real-world customer psychology, objection handling, and negotiation — backed by UNT's complete sourcing and digital branding ecosystem.",
  training_cta: 'Book Team Consultation',
  training_format_heading: 'Choose Your Delivery Format',
  training_active_label: 'Active',
  training_formats: trainingFormats,
  training_curriculum_heading: 'Curriculum & Training Modules',
  training_curriculum: trainingCurriculum,
  training_ecosystem_heading: 'The UNT Ecosystem Advantage',
  training_ecosystem_desc: 'Unlike generic training courses, UNT provides an active commercial ecosystem so your sales team learns with real products, real supply chains, and digital branding assets:',
  training_ecosystem_items: trainingEcosystemItems,
  training_director_cta: 'Consult With Our Sales Director',
  builder_badge: 'Interactive Custom Solution Builder', builder_title: 'Build Your Custom', builder_highlight: 'UNT Service Package',
  builder_desc: 'Configure your desired procurement scope, origin country, logistics speed, and ecosystem add-ons to preview instant timeline & compliance metrics.',
  builder_core_label: '1. Select Core Business Need', builder_services: builderServices,
  builder_origin_label: '2. Origin Country', builder_countries_text: 'Japan\nSouth Korea\nMalaysia\nVietnam\nLaos\nChina',
  builder_freight_label: '3. Freight Speed', builder_freight_options: builderFreightOptions,
  builder_addons_label: '4. Ecosystem Add-ons', builder_addons: builderAddons,
  matrix_badge: 'Comparative Sourcing Matrix', matrix_title: 'Why Businesses Choose', matrix_highlight: 'UNT Sourcing',
  matrix_unt_tab: 'UNT Ecosystem', matrix_traditional_tab: 'Traditional / Self-Import', matrix_rows: sourcingMatrixRows,
  faq_badge: 'Frequently Asked Questions', faq_title: 'Got Questions About', faq_highlight: 'UNT Services?',
  faq_desc: 'Search or select a category below for instant answers regarding custom sourcing, GDCE customs clearance, local stock delivery, and sales workshops.',
  faq_search_placeholder: 'Search FAQs (e.g. GDCE, MOQ, delivery, training)...', faq_tab_all: 'All FAQs',
  faq_tab_customs: 'GDCE & Customs', faq_tab_sourcing: 'Sourcing & MOQs', faq_tab_delivery: 'Local Delivery', faq_tab_training: 'Sales Training', faq_items: faqList,
  estimator_title: 'Interactive Sourcing Estimator', estimator_desc: 'Calculate lead times, logistics, & Cambodian import permit requirements',
  estimator_badge: 'B2B Sourcing Tool', estimator_category_label: '1. Product Category', estimator_origin_label: '2. Manufacturing Origin',
  estimator_volume_label: '3. Estimated Lot Volume', estimator_oem_label: 'Requires Turnkey OEM / Custom Brand Re-packaging (+14 Days R&D)',
  estimator_lead_label: 'Est. Delivery Lead Time', estimator_route_label: 'Logistics Shipping Route', estimator_clearance_label: 'Ministry Clearances Secured',
  estimator_note: "Estimates based on Unique Noble Trading Co., Ltd.'s established trade lane frequencies.", estimator_cta: 'Lock In Formal Quotation',
};

export const EMPTY_TRANSLATIONS = Object.fromEntries(
  Object.entries(DEFAULTS).map(([key, value]) => [key, Array.isArray(value) ? [] : ''])
);

export const KHMER_COUNTRY_DEFAULTS: Record<string, any> = {
  KH: {
    name: 'កម្ពុជា',
    niche: 'ការចែកចាយក្នុងស្រុក ផលិតផលសម្គាល់ភូមិសាស្ត្រ និងមជ្ឈមណ្ឌលភស្តុភារតំបន់',
    seaTransit: '១ – ២ ថ្ងៃ',
    airTransit: 'ក្នុងថ្ងៃ / បន្ទាន់',
    standards: ['អនុលោមតាម GDCE', 'វិញ្ញាបនបត្រពាណិជ្ជកម្ម', 'ទទួលស្គាល់ដោយក្រសួងសុខាភិបាល'],
    topProducts: ['ម្រេចកំពត និងផលិតផលកសិកម្ម', 'ទំនិញប្រើប្រាស់ក្នុងស្រុក', 'ស្តុកដុំក្នុងស្រុក'],
    desc: 'បណ្តាញឃ្លាំងកណ្តាល និងការដឹកជញ្ជូនដល់ទីតាំងផ្ទាល់នៅភ្នំពេញ និងគ្រប់ ២៥ រាជធានី-ខេត្ត។',
  },
  JP: {
    name: 'ជប៉ុន',
    niche: 'ការថែរក្សាស្បែកលំដាប់ខ្ពស់ កូឡាជែន និងភេសជ្ជៈមុខងារ',
    seaTransit: '១២ – ១៤ ថ្ងៃ',
    airTransit: '៣ – ៥ ថ្ងៃ',
    standards: ['អនុម័តដោយ PMDA', 'ISO 22000', 'ទទួលស្គាល់ដោយ GMP'],
    topProducts: ['សេរ៉ូមកូឡាជែនពន្យារភាពចាស់', 'ម្សៅតែបៃតង និងតែមុខងារ', 'អាហារបំប៉ន Placenta និង NMN'],
    desc: 'ភាពជាដៃគូរោងចក្រផ្ទាល់នៅតូក្យូ អូសាកា និងហ្វូគូអូកា។ ការផលិតរបស់ជប៉ុនធានានូវភាពបរិសុទ្ធនៃរូបមន្ត និងការត្រួតពិនិត្យគុណភាពយ៉ាងម៉ឹងម៉ាត់។',
  },
  KR: {
    name: 'កូរ៉េខាងត្បូង',
    niche: 'K-Beauty ថែរក្សាស្បែក និងផលិតផលសុខភាពទាន់សម័យ',
    seaTransit: '១០ – ១២ ថ្ងៃ',
    airTransit: '២ – ៤ ថ្ងៃ',
    standards: ['ស្តង់ដារ MFDS (KFDA)', 'CGMP', 'ISO 22716'],
    topProducts: ['សេរ៉ូមផ្តល់សំណើម Cica', 'ឡេការពារកម្តៅថ្ងៃ Glass-Skin SPF50+', 'យិនស៊ិនក្រហមចាញ់'],
    desc: 'ក្រុមការងារលទ្ធកម្មផ្ទាល់នៅសេអ៊ូល និងអ៊ីនឈុន។ ទទួលបានរូបមន្ត K-Beauty ទាន់សម័យ និងរោងចក្រ OEM/ODM។',
  },
  VN: {
    name: 'វៀតណាម',
    niche: 'កសិផលពិសេស កាហ្វេ គ្រឿងទេស និងការវេចខ្ចប់',
    seaTransit: '៣ – ៥ ថ្ងៃ',
    airTransit: '១ – ២ ថ្ងៃ',
    standards: ['វិញ្ញាបនបត្រ VFA', 'ISO 9001', 'ស្តង់ដារ VietGAP'],
    topProducts: ['គ្រាប់កាហ្វេ Robusta គុណភាពខ្ពស់', 'ស្វាយកែវរំអៀត និងផ្លែឈើក្រៀម', 'ប្រអប់វេចខ្ចប់បរិស្ថាន'],
    desc: 'ការដឹកជញ្ជូនតាមផ្លូវគោកឆ្លងដែន និងផ្លូវសមុទ្រលឿនបំផុត។ តម្លៃសមរម្យសម្រាប់ទំនិញកសិកម្ម និងអាហារវេចខ្ចប់។',
  },
  LA: {
    name: 'ឡាវ',
    niche: 'ផលិតផលកសិកម្មសរីរាង្គ តែ រ៉ែ និងសិប្បកម្ម',
    seaTransit: '២ – ៤ ថ្ងៃ (ផ្លូវដែក និងរថយន្ត)',
    airTransit: '១ – ២ ថ្ងៃ',
    standards: ['អនុម័តដោយ Lao FDA', 'ISO 9001', 'អនុលោមភាពពាណិជ្ជកម្មអាស៊ាន'],
    topProducts: ['គ្រាប់កាហ្វេភ្នំពិសេស', 'តែសរីរាង្គ និងគ្រឿងទេស', 'សូត្រ និងសម្លៀកបំពាក់បៃតង'],
    desc: 'ច្រកពាណិជ្ជកម្មផ្លូវគោកផ្ទាល់តាមវៀងច័ន្ទ។ ការតភ្ជាប់ភស្តុភារឆ្លងដែនលឿនរហ័សរវាងកម្ពុជា និងឡាវ។',
  },
  CN: {
    name: 'ចិន',
    niche: 'ការវេចខ្ចប់គ្រឿងសម្ភារៈសម្រស់ OEM អេឡិចត្រូនិក និងទំនិញដុំ',
    seaTransit: '៧ – ១០ ថ្ងៃ',
    airTransit: '២ – ៤ ថ្ងៃ',
    standards: ['ចុះបញ្ជី NMPA', 'ISO 13485', 'ស្តង់ដារ CE & CCC'],
    topProducts: ['ដបគ្រឿងសម្អិត Airless', 'ឧបករណ៍ពន្លឺបំប៉នស្បែក LED', 'ប្រអប់រឹងបោះពុម្ពតាមតម្រូវការ'],
    desc: 'ការសវនកម្មរោងចក្រផ្ទាល់នៅក្វាងទុង ចឺជាំង និងជាំងស៊ូ។ ប្រភពចម្បងសម្រាប់ការផលិតពុម្ពវេចខ្ចប់ OEM និងទំនិញដុំ។',
  },
  MY: {
    name: 'ម៉ាឡេស៊ី',
    niche: 'អាហារ ព្រេង និងផលិតផលអនាម័យផ្ទាល់ខ្លួន standard Halal',
    seaTransit: '៧ – ៩ ថ្ងៃ',
    airTransit: '២ – ៣ ថ្ងៃ',
    standards: ['JAKIM Halal', 'MPOB Certified', 'HACCP & GMP'],
    topProducts: ['កាហ្វេស 3-in-1', 'ប្រេងដូងបរិភោគ', 'សាប៊ូកក់សក់ និងសាប៊ូតួខ្លួនសរីរាង្គ'],
    desc: 'ការតភ្ជាប់ភស្តុភាររវាងកំពង់ផែ Klang និងព្រះសីហនុ។ ប្រភពផលិតផលប្រើប្រាស់ និងគ្រឿងសម្អិត Halal។',
  },
};

export const KHMER_STRUCTURE_DEFAULTS = {
  origin_countries: countryContentDefaults.map((country) => ({
    code: country.code,
    name: KHMER_COUNTRY_DEFAULTS[country.code]?.name || country.name,
    niche: KHMER_COUNTRY_DEFAULTS[country.code]?.niche || country.niche,
    seaTransit: KHMER_COUNTRY_DEFAULTS[country.code]?.seaTransit || country.seaTransit,
    airTransit: KHMER_COUNTRY_DEFAULTS[country.code]?.airTransit || country.airTransit,
    standards: KHMER_COUNTRY_DEFAULTS[country.code]?.standards || country.standards,
    topProducts: KHMER_COUNTRY_DEFAULTS[country.code]?.topProducts || country.topProducts,
    desc: KHMER_COUNTRY_DEFAULTS[country.code]?.desc || country.desc,
  })),
  product_categories: productCategories.map(() => ({ title: '', count: '' })),
  product_benefits: productBenefits.map(() => ({ title: '', desc: '' })),
  sourcing_steps: sourcingSteps.map((step) => ({ num: step.num, title: '', subtitle: '', desc: '' })),
  training_formats: trainingFormats.map((item) => ({ id: item.id, title: '', desc: '' })),
  training_curriculum: trainingCurriculum.map(() => ''),
  training_ecosystem_items: trainingEcosystemItems.map(() => ''),
  builder_services: builderServices.map((item) => ({ id: item.id, label: '', desc: '' })),
  builder_freight_options: builderFreightOptions.map((item) => ({ id: item.id, label: '', sub: '' })),
  builder_addons: builderAddons.map((item) => ({ id: item.id, label: '', tag: '' })),
  matrix_rows: sourcingMatrixRows.map(() => ({ feature: '', unt: '', traditional: '' })),
  faq_items: faqList.map((item) => ({ category: item.category, q: '', a: '' })),
};

export function servicesEditorData(language: 'en' | 'km', saved: Record<string, any> | null | undefined) {
  if (language === 'en') return { ...DEFAULTS, ...(saved ?? {}) };
  const merged = { ...EMPTY_TRANSLATIONS, ...KHMER_STRUCTURE_DEFAULTS, ...(saved ?? {}) } as any;
  for (const key of Object.keys(KHMER_STRUCTURE_DEFAULTS) as Array<keyof typeof KHMER_STRUCTURE_DEFAULTS>) {
    if (!Array.isArray(merged[key]) || merged[key].length === 0) merged[key] = KHMER_STRUCTURE_DEFAULTS[key];
  }
  return merged;
}

export const TABS = ['Header', 'Product Sales', 'Sourcing', 'Sales Training', 'Advanced Content'] as const;
export type Tab = typeof TABS[number];
