import { TRAINING_TRACKS } from '@/src/data/mockData';
import { RECENT_ACTIVITIES, UPCOMING_SESSIONS } from '@/src/pages/training/TrainingPromosSchedule';

export const DEFAULTS = {
  badge: 'UNT Trade Capacity Building Institute',
  headline: 'Mastering the Art of Global Commerce',
  subheadline: "Elevate your commercial team's B2B negotiation skills, buyer psychology, key account retention, and international supply chain management.",
  hero_gallery_cta: 'Explore Live Activity & Media Gallery',
  hero_reserve_cta: 'Reserve Corporate Masterclass',
  stat1_value: '1,200+', stat1_label: 'Professionals Certified',
  stat2_value: '4.9 / 5.0', stat2_label: 'Average Course Rating',
  stat3_value: '15+', stat3_label: 'Senior Trade Instructors',
  stat4_value: '34%', stat4_label: 'Avg 90-Day Conversion Lift',
  tracks_badge: 'Curriculum',
  tracks_heading: 'Specialized B2B Commercial Tracks',
  tracks_sub: 'Select a track below to review full module syllabi, target audience criteria, and enrollment schedules.',
  tracks: TRAINING_TRACKS,
  schedule_live_label: 'Live Updates',
  schedule_badge: 'Interactive Schedule & Enrollment',
  schedule_heading: 'Upcoming Corporate Training Sessions',
  schedule_sub: 'Review available cohorts, seat capacity, schedules, and group corporate pricing.',
  upcoming_sessions: UPCOMING_SESSIONS,
  recent_activities: RECENT_ACTIVITIES,
  gallery_badge: 'Live Activity & Media Showcase',
  gallery_heading: 'See Our Sales Academy In Action',
  gallery_sub: 'Explore real workshop sessions, live negotiation video previews, hands-on roleplay labs, and corporate graduation ceremonies.',
  gallery_tab_all: 'All Activities',
  gallery_tab_workshops: 'Workshops',
  gallery_tab_videos: 'Video Previews',
  gallery_tab_negotiation: 'Negotiation Labs',
  gallery_tab_graduation: 'Graduations',
  gallery_view_gallery: 'View Gallery',
  gallery_watch_video: 'Watch Full Video',
  gallery_browse_album: 'Browse Album',
  gallery_cta_badge: 'Live Enterprise Enrollment',
  gallery_cta_heading: 'Want to Host This Interactive Workshop for Your Sales Team?',
  gallery_cta_desc: 'We deliver custom on-site activity bootcamps with simulated negotiation roleplay tailored to your company catalog.',
  gallery_cta_button: 'Schedule On-Site Workshop',
  gallery_video_enroll_cta: 'Enroll Team in This Masterclass',
  gallery_album_book_cta: 'Book Workshop',
  activities: [],
  bootcamp_badge: 'In-House Corporate Solutions',
  bootcamp_heading: 'Need a Private Masterclass for Your Commercial Team?',
  bootcamp_desc: 'We deliver custom on-site workshops tailored to your industry, product catalog, and specific negotiation challenges directly at your Phnom Penh corporate headquarters.',
  bootcamp_cta: 'Book Corporate Session',
};

export const TABS = ['Hero', 'Stats', 'Schedule', 'Gallery', 'Bootcamp'] as const;
export type Tab = typeof TABS[number];
